name: Cypress Tests 

on:
  push:
    branches: [ "main", "new-features" ] 
  pull_request:
    branches: [ "main", "new-features" ] 
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    services:
        mysql:
          image: mysql:5.7 # Escolha a versão desejada
          ports:
            - 3306:3306
          env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  

    steps:
      - name: Checkout code # Faz o checkout do seu código para o ambiente do runner
        uses: actions/checkout@v4

      - name: Setup Node.js # Configura o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2' 

      - name: Install dependencies
        run: npm install

      - name: Install Cypress dependencies # Instala as dependências específicas do Cypress
        run: npx cypress install

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -hlocalhost -P3306 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Create Database Schema
        run: mysql -hlocalhost -P3306 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}  ${{ secrets.DB_NAME }} < sql/schema.sql

      - name: Start local server
        run: npm run start &
        env:
          MYSQL_URI: ${{ secrets.MYSQL_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          FACEBOOK_CALLBACK_LOGIN_URL: ${{ secrets.FACEBOOK_CALLBACK_LOGIN_URL }}
          FACEBOOK_CALLBACK_SIGNUP_URL: ${{ secrets.FACEBOOK_CALLBACK_SIGNUP_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_LOGIN_URL: ${{ secrets.GOOGLE_CALLBACK_LOGIN_URL }}
          GOOGLE_CALLBACK_SIGNUP_URL: ${{ secrets.GOOGLE_CALLBACK_SIGNUP_URL }}

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8081

      - name: Cypress run
        uses: cypress-io/github-action@v6 